### ISSUE TITLE
Question about inference speed.

### ISSUE THREAD

**Issue by YecanLee** [YuchuanTian/U-DiT#10]
Hi, thank you for your amazing work! May I ask did you ever try to use a fast sampler? According to the `--num-sampling-steps`, it seems like the model is using a slow sampler with `250` sampling steps. May I ask did the fast sampler affect the model's performance? Based on my own test on one single A100 and one single RTX-4090, the inference speed of this model is not as fast as other models like `U-ViT` or `VAR`. May I ask did I do something wrong?

**Comment by YuchuanTian** [comment]
It's because we are following DiT that uses conventional DDIM as sampler. U-ViT uses DPM-Solver on ImageNet 256 that is stronger. Plus, the results reported by U-ViT and VAR requires intensive training and I think it's not fairly comparable to ours. We have adapted U-ViT on our setting (400K) and find that our U-DiT is more performant than U-ViT:

U-DiT-B 22.2GFLOPs FID 16.64
U-ViT-L 76.4GFLOPs FID 21.22

**Comment by YecanLee** [comment]
Thank you so much for your quick and detailed reply! I doubled check the other two papers and they indeed both requires intensive training. I understand now that the choice of `DDIM` sampler came from following the original design of `DiT` now. Thank you for your amazing work again!

**Comment by YuchuanTian** [comment]
Thank you too!
