### ISSUE TITLE
Some variables do not match the U structure

### ISSUE THREAD

**Issue by zhanhaolin1997** [YuchuanTian/U-DiT#8]
Hello, the logic of some variables in the code is confusing, such as using hidden size * 2 instead of hidden size when defining the last decoder
1. https://github.com/YuchuanTian/U-DiT/blob/e53e0b447b7336aed06a71f933e0075f03183b01/udit_models.py#L639

And why use c2 instead of c1 in the forward process of the last decoder
2. https://github.com/YuchuanTian/U-DiT/blob/e53e0b447b7336aed06a71f933e0075f03183b01/udit_models.py#L741

I think it doesn't match the corresponding encoder part
1. https://github.com/YuchuanTian/U-DiT/blob/e53e0b447b7336aed06a71f933e0075f03183b01/udit_models.py#L613
2. https://github.com/YuchuanTian/U-DiT/blob/e53e0b447b7336aed06a71f933e0075f03183b01/udit_models.py#L713

**Comment by YuchuanTian** [comment]
Using dim*2 is actually a practice in Restormer:

https://github.com/swz30/Restormer/blob/df766d5521afd21cce56e24159f300b30ebf3fb0/basicsr/models/archs/restormer_arch.py#L233

Besides, a specific reason to use dim*2 for the last decoder of U-DiT is that the output is information-intensive. The output dimension is double the input dimension (the output is the concatenation of [denoised img; sigma])

Thus, to align the condition for dim*2, we plug c2 into the last decoder block instead of c1.

**Comment by zhanhaolin1997** [comment]
OK，thank you. 

Another small question is why the modules in U_DiTBlock are repeated twice. I think this is equivalent to defining the network with depth * 2

**Comment by YuchuanTian** [comment]
Yes, I think that's true. We are following norms from previous low-level vision models that contain two modules in one block. That's why we have the module repeated twice. Sorry for getting you puzzled.

**Comment by zhanhaolin1997** [comment]
If possible, we may be able to communicate details through Wechat. I have sent you an email containing my WeChat account.
